### ISSUE TITLE
Uncaught (in promise) RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by zjfcool** [perliedman/leaflet-raster#1]
Hi!
When I used this library, I found an error.
(Uncaught (in promise) RangeError: Offset is outside the bounds of the DataView);
My code:
```
<template></template>

<script>
import Pipeline from "raster-blaster/src/pipeline";
import * as PipelineSteps from "raster-blaster/src/pipeline-steps";
import WebGlRenderer from "raster-blaster/src/webgl/webgl-renderer";
import * as GeoTIFF from "geotiff";
import RasterLayer from "@/plugins/leaflet-raster";
import axios from "axios";
export default {
  name: "TiffToCanvasLayer",
  data() {
    return {};
  },
  methods: {
    init() {
      const pipeline = new Pipeline(
        [
          // VARI vegetation index
          new PipelineSteps.GrayScale("($g - $r) / ($g + $r - $b)"),
          // Stretch histogram to between index 0.2 to 0.8
          new PipelineSteps.SmoothstepContrast(0.2, 0.8),
          // Map grayscale to color scale Red-Yellow-Green
          new PipelineSteps.ColorMap("RdYlGn"),
          // Copy alpha band directly to alpha channel
          new PipelineSteps.BandsToChannels("a")
        ],
        {
          bands: "rgba",
          dataType: "Uint8"
        }
      );

      const renderer = new WebGlRenderer();

      const renderFn = (canvas, getRasters) =>
        renderer.render(canvas, pipeline, getRasters);
      axios("wrfout.tif", {
        responseType: "arraybuffer"
      }).then(res => {
        GeoTIFF.fromArrayBuffer(res.data).then(tiff => {
          const rasterFn = (nwSe, size) =>
            tiff.readRasters({
              bbox: [nwSe[0].lng, nwSe[1].lat, nwSe[1].lng, nwSe[0].lat],
              width: size.x,
              height: size.y
            });
          const geotiffLayer = new RasterLayer(tiff, rasterFn, renderFn);
          geotiffLayer.addTo(this.$parent.mapObject)
          console.log(geotiffLayer);
        });
      });
    }
  },
  mounted() {
    this.init();
  }
};
</script>
```

**Comment by perliedman** [comment]
Hi there! Nice to see someone using this library although it is in very early development!

Hard to say without seeing a stack trace, but it *does* sound like that error comes from GeoTIFF.js and not Leaflet Raster, since this library does not access data views and such. I have seen similar errors in GeoTIFF.js with some TIFF files.

**Comment by zjfcool** [comment]
> Hi there! Nice to see someone using this library although it is in very early development!
> 
> Hard to say without seeing a stack trace, but it _does_ sound like that error comes from GeoTIFF.js and not Leaflet Raster, since this library does not access data views and such. I have seen similar errors in GeoTIFF.js with some TIFF files.

Hi，This error occurred while executing this code
`geotiffLayer.addTo(this.$parent.mapObject)`
That's strange....

**Comment by perliedman** [comment]
Yes, sure, but did you see the stack trace? I bet it ends up in GeoTIFF.js.

The process of loading tiles (and therefor accessing the GeoTIFF's raster data) is not started until you add the layer to the map, so it is totally reasonable the error would come up from this call.

Please post a stack trace or a code example I can try myself if you need me to dig into this further.

**Comment by zjfcool** [comment]
Yes,finally,end up at here:
![image](https://user-images.githubusercontent.com/17940669/66793299-58926000-ef2f-11e9-8419-5d636f1ced74.png)

**Comment by zjfcool** [comment]
And,do you know any other ways to load TIFF files in leaflet?

I tried several ways:

1. Generate the TIFF file into geojson, and load it. But because the isosurface is interpolated, there will be some situations where the boundary cannot be rendered. Of course, the finer the TIFF grid is, the better the effect will be, but it will always be rendered, and the TIFF file will become larger accordingly. For example, the TIFF file is in Chinese shape, and some peripherals will not be rendered.

My sample code [address:](https://github.com/zjfcool/leaflet-learn/blob/master/src/components/TiffToGeojsonLayer.vue)

2. Transforming TIFF files into pictures is no problem when it is first generated. When the map is translated and scaled, it will be rendered incorrectly when it is loaded the second time.
[My sample code address:](https://github.com/zjfcool/leaflet-learn/blob/master/src/components/TiffToImageLayer.vue)

**Comment by perliedman** [comment]
Ok, so you should file a bug with GeoTIFF.js if possible.

I think there are some other GeoTIFF plugins, but last time I looked they were not very promising, that is one of the reasons I started working on this.

Given the huge number of polygons required, I don't think you will find converting a GeoTIFF to GeoJSON very productive, and the same goes for converting it into another image: those files will be huge, which is why a cloud optimized GeoTIFF is attractive.

**Comment by zjfcool** [comment]
ok，thank you.
